# Generated by Django 4.2.16 on 2024-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='blog_media/'),
        ),
    ]
